version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
configuration: Debug
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
environment:
  nodejs_version: "11.10.1"
  COVERALLS_REPO_TOKEN:
    secure: ZzbSvqtdI0JnPYSmj8N4ladrU8Na5Tjj2Qe0VrBPFbzHfXRJ1LiuDZpyCJWxbdN/
install:
  # Install repo specific stuff here
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install
before_build:
  - dotnet restore
  - nuget install -Verbosity quiet opencover -Version 4.6.519 -OutputDirectory tools
  - nuget install -Verbosity quiet coveralls.net -Version 0.7.0 -OutputDirectory tools
build_script:
  - dotnet build -c Debug /p:DebugType=full
test_script:
  # restore packages for our unit tests
  - cmd: dotnet restore ./src/Gardenalogue.Test/Gardenalogue.Test.csproj --verbosity m
  # run the unit tests
  - cmd: dotnet test  
