version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
environment:
  nodejs_version: "11.10.1"
install:
  # Install repo specific stuff here
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install
before_build:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # Display .NET Core version
  - cmd: dotnet --version
  # Install sonarscanner
  - cmd:dotnet tool install --global dotnet-sonarscanner
  # Display minimal restore text
  - cmd: dotnet restore ./Gardenalogue.Web/Gardenalogue.Web.csproj --verbosity m  
build_script:
  - cmd: dotnet build src
after_build:
  # For once the build has completed
artifacts:
 #- path: '\src\bin\Debug\netcoreapp2.2\publish'
 #  name: WebSite
 #  type: WebDeployPackage
clone_depth: 1
test_script:
  # restore packages for our unit tests
  - cmd: dotnet restore ./Gardenalogue.Test/Gardenalogue.Test.csproj --verbosity m
  # run the unit tests
  - cmd: dotnet test
on_finish :
  # any cleanup in here
deploy: off