version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
configuration: Debug
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
environment:
  nodejs_version: "11.10.1"

  coverlet_output: "%APPVEYOR_BUILD_FOLDER%/build/Coverlet.Coverage.OpenCover.xml"
  
  CODECOV_TOKEN:
    secure: 6/b/L0Y3KaHvhT4SbEnrtOisKfJkmiykvYEeuJLcWNY/kQKvhHRl1/TlLEOskVfp

build: off
test: off

install:
  # Install repo specific stuff here
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install
  - docker version
before_build:
  cmd: >-
    choco install codecov
    
    dotnet restore src
build_script:
  ps: >-
    dotnet build src
    
    dotnet test src /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput="$env:coverlet_output"
    
    codecov -f "$env:coverlet_output" -t "$env:CODECOV_TOKEN"

    docker build -t me/myfavoriteapp .
